#!/bin/bash

if [ "$#" -lt 1 ]; then
    echo "Expecting a problem name" >&2
    exit 2
fi

problem_name="$1"
shift

temp_dir=".build/submission"
problems_dir="kattis/src/kattis/problems"
shared_dir="kattis/src/kattis/shared"

mkdir -p $temp_dir

cat $problems_dir/$problem_name.hpp \
    | grep -v "#pragma once" \
    > $temp_dir/$problem_name.cpp

echo "using namespace _$problem_name;" >> $temp_dir/$problem_name.cpp

cat $problems_dir/main.cpp \
    >> $temp_dir/$problem_name.cpp

shared_files=$(awk -F'"' "/#include \"/{print \"${shared_dir}/\"\$2}" $temp_dir/$problem_name.cpp)

if ! command -v python3 &> /dev/null; then
    python scripts/submit.py "$@" $temp_dir/$problem_name.cpp $shared_files
else
    python3 scripts/submit.py "$@" $temp_dir/$problem_name.cpp $shared_files
fi

rm -rf $temp_dir
